project:
  type: website
  output-dir: _site

website:
  title: "Orbitus Robotics"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    center: "© 2025 Orbitus Robotics"

format:
  html:
    theme: cosmo
