name: Build and deploy (Hugo + TailBliss)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.128.2"
          extended: true

      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          fi

      - name: Build site (prefer npm run build if available)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f package.json ] && npm run | grep -qE "^[[:space:]]+build"; then
            npm run build -- --baseURL "${{ steps.pages.outputs.base_url }}/"
          else
            hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
          fi
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENABLEGITINFO: "true"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
